
language: php

php:
  - 7.0

before_install:
  - cd yii2

install:
  - composer self-update
  - composer global require --prefer-source fxp/composer-asset-plugin:~1.1.1
  - composer install

script: php yii2/vendor/codeception/codeception/codecept run