
language: php

php:
  - 7.0

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"

services:
  - memcached

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

before_install:
  - cd yii2

install:
  - |
    if [ -n "$GITHUB_APITOKEN" ]; then
      composer config github-oauth.github.com $GITHUB_APITOKEN;
      echo 'auth.json' >> .git/info/exclude
    fi

  - travis_retry composer self-update
  - travis_retry composer global require --prefer-source fxp/composer-asset-plugin:~1.1.1
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

script: php yii2/vendor/codeception/codeception/codecept run