
language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_install:
  - COMPOSER_ROOT_VERSION=dev-master composer install
  - cd yii2

install:
  - composer self-update
  - composer install

script: php yii2/vendor/codeception/codeception/codecept run