sudo: true

language: php

php:
  - 7.0

services:
  - memcached

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - cd yii2

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

#install:
#  - travis_retry composer self-update && composer --version
#  - travis_retry composer global require --prefer-source fxp/composer-asset-plugin:~1.1.1
#  - export PATH="$HOME/.composer/vendor/bin:$PATH"
#  - travis_retry composer install --dev --prefer-dist --no-interaction

script: php yii2/vendor/codeception/codeception/codecept run